"""added an email column in our user table

Revision ID: 011658214c9e
Revises: ad7c58964676
Create Date: 2021-09-25 11:45:12.335577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011658214c9e'
down_revision = 'ad7c58964676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
